### ISSUE TITLE
Question about Eq. (1)

### ISSUE THREAD

**Issue by luzzou** [GeeeG/CloudPose#13]
Hello,  thank you for your great work. I have a question about Eq.(1) in your paper.
Is the "theta" in Formula 1 redundant? Because I find that it is not written in other materials.

![Screenshot from 2020-11-13 11-29-42](https://user-images.githubusercontent.com/29935938/99025360-9420b300-25a3-11eb-9914-2343ae46ae34.png)

**Comment by GeeeG** [comment]
Hi, thank you for the question. 
In general, theta denotes the amount of rotation around its rotation axis, and it is needed to calculate its corresponding rotation matrix.
One reference you can check is "Rotation Averaging" by Hartley et al. (https://link.springer.com/article/10.1007/s11263-012-0601-0), in equation (3), they don't have the theta in the denominator because their "v" is a unit vector, while the "r" in our case is not, that's why we divide the last two terms on the right side with its amount of rotation.

**Comment by luzzou** [comment]
Got it, thanks. 
By the way, I have another question about Table 1. 
The ADS results you reported for PoseCNN and DenseFusion are much better than the original papers,
i.e., PoseCNN 93.6 v.s. 93.0
       DenseFusion 93.9 v.s. 93.1
Did you retrain these two methods to get performance enhancement?

![Screenshot from 2020-11-18 20-56-56](https://user-images.githubusercontent.com/29935938/99533305-9ee2aa00-29e0-11eb-865f-b6d5f3f41d14.png)

**Comment by GeeeG** [comment]
For the evaluation results for this paper, we excluded some test segment samples for all three methods because the number of points in those segments is too low (less than 256), and this caused the differences.

**Comment by luzzou** [comment]
I see, thanks for your reply!
