### ISSUE TITLE
Slow encoding

### ISSUE THREAD

**Issue by gilad011** [GeeeG/CloudPose#14]
I am encoding my dataset to .tfrecord file.
the second script: 2_dataset_to_tfrecord.py take a lot of time to process while the first is very fast.
for example: for 3000 sample to encode it take up to 3 days!! is it reasonable? it comes from the FPS?

**Comment by GeeeG** [comment]
How many points do you have in your original sample? FPS is the most expensive part in the script. 
If the original segment has many points, which results in slow FPS, I would suggest to first use random down sampling on the original segment, then use FPS

**Comment by gilad011** [comment]
The original cloud is ranges from 10k to 90k points. 
Is it too much to run FPS to choose 2048 points for example? 
What is the ratio that provide normal running time? 

Another question, could it happen because of the one shot iterator in tf? Can I run the encoding on the gpu?

**Comment by GeeeG** [comment]
10k is kinda large and 90k is very large, at least based on my experience. Because each iteration FPS needs to calculate the distance from the current point to all other remaining point in the segment, this is very expensive with a large number. I would suggest to try to first down sample to e.g. 5k with random downsampling, then do FPS. Then check FPS segment visually to see if it still capture the surface well, you could try with different numbers for random ds to find an optimal one, both time and quality wise.

I run the encoding on cpu, so I'm not sure how it is on gpu. I am not sure whether the tf iterator would also contribute to your problem, but based on my experience, most likely the main problem is FPS.

**Comment by gilad011** [comment]
I did the random sampling according to your suggestion. so that the FPS will get 5K points at a time. HOWEVER, the encoding is still very slow, while the first 200 samples are encoded fast, and as long as more sample were encoded the time to process each sample is increased. very strange phenomenon, have you came across it? can it be resulted from slow serialization?  can it be related to WINDOWS?

see this thread: https://github.com/tensorflow/tensorflow/issues/4467

**Comment by GeeeG** [comment]
do you observe a memory increase while encoding (with command "htop" in ubuntu, for example), I don't recall encounter this problem as serious as you experienced, and I run the encoding in linux
